<?php
// ONE-SHOT — create "Cold Batch 05 — HVAC + Landscaping TX/FL" in Instantly by
// cloning Batch 02's proven config (A/B sequence + CAN-SPAM footer + schedule +
// mailboxes + tracking-off), then upload 156 RECEIVING-validated leads + Leo's
// rotating seed. Dry-run by default; ?confirm=1 creates + uploads (leaves DRAFT).
// DELETE THIS FILE after use.
declare(strict_types=1);
define('CRM_ENTRY',1);
require_once __DIR__.'/lib/db.php';
require_once __DIR__.'/lib/instantly.php';
if (($_GET['t']??'')!=='e8195bbd807601b3a9174cd7abc0caf12e1c9d24d3ca8c13'){http_response_code(403);exit('forbidden');}
header('Content-Type: text/plain; charset=utf-8');
@set_time_limit(0); @ini_set('max_execution_time','0');
while(ob_get_level()>0){@ob_end_flush();} @ob_implicit_flush(true);
$confirm=($_GET['confirm']??'')==='1';

$BATCH02_ID='1a611738-c631-4af6-a50c-d8c9a6accc22';
$NAME='Cold Batch 05 — HVAC + Landscaping TX/FL';
$SEED='szachtman.leandro@gmail.com'; // Batch 05 rotation (mod 4)
$DAILY_LIMIT=30; // ramp slow

$leads=[
  ['email'=>'samuel@airtechofhouston.com','first_name'=>'Samuel','last_name'=>'Allison','company_name'=>'Air Tech of Houston AC & Plumbing','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 832-680-5546','website'=>'https://www.airtechofhouston.com/locations/houston-tx/%3Futm_source%3Dgoogle-gbp%26utm_medium%3Dorganic%26utm_campaign%3D*19*air-tech-houston'],
  ['email'=>'fernandobetancourt@uptownac.com','first_name'=>'there','last_name'=>'','company_name'=>'Uptown Heating & Air Conditioning','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 832-709-0236','website'=>'https://www.uptownac.com/'],
  ['email'=>'jane@spacecityhvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Space City Mechanical','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 713-433-3339','website'=>'http://www.spacecityhvac.com/'],
  ['email'=>'scott@leethompsonac.com','first_name'=>'Scott','last_name'=>'Thompson','company_name'=>'The Lee Thompson Co','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 713-869-9895','website'=>'https://www.leethompsonac.com/'],
  ['email'=>'james@richmondsair.com','first_name'=>'there','last_name'=>'','company_name'=>'Richmonds Air','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 713-999-4735','website'=>'https://www.richmondsair.com/%3Futm_source%3Dgmb%26utm_medium%3Dwebsite'],
  ['email'=>'ruben@masteracandheat.com','first_name'=>'there','last_name'=>'','company_name'=>'Master AC and Heat, LLC- The Heights','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 713-750-9769','website'=>'http://masteracandheat.com/'],
  ['email'=>'hadi@hagenrg.com','first_name'=>'there','last_name'=>'','company_name'=>'Hage Energy','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 713-560-0600','website'=>'https://www.hagenrg.com/'],
  ['email'=>'david.rivera@ehshvac.com','first_name'=>'David','last_name'=>'Rivera','company_name'=>'Efficient Home Solutions of Dallas','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-612-7493','website'=>'https://ehshvac.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dehsdallasfbmopo'],
  ['email'=>'ricky@callberrybest.com','first_name'=>'there','last_name'=>'','company_name'=>'Berry Best Cooling & Heating','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 972-928-9482','website'=>'https://www.callberrybest.com/'],
  ['email'=>'brennan@thechillbrothers.com','first_name'=>'Brennan','last_name'=>'Mulcahy','company_name'=>'The Chill Brothers','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 844-512-4455','website'=>'https://thechillbrothers.com/ac-repair-service-dallas/'],
  ['email'=>'edgar@astardfw.com','first_name'=>'Edgar','last_name'=>'Esparza','company_name'=>'Air Force One Plumbing Heating & Air, now part of A-Star Air Conditioning & Plumbng','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 469-476-4846','website'=>'https://astardfw.com/air-force-one-plumbing-heating-and-air/'],
  ['email'=>'parts@otp-hvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Open To Public HVAC Parts','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-340-9421','website'=>'https://otp-hvac.com/'],
  ['email'=>'sshel@mbkiser.com','first_name'=>'Scott','last_name'=>'Shelton','company_name'=>'M. B. Kiser Heating & Air Conditioning Co. Inc.','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-823-9958','website'=>'https://mbkiser.com/'],
  ['email'=>'aquigley@quigleyac.com','first_name'=>'Ashley','last_name'=>'Quigley','company_name'=>'Quigley Heating & Air Conditioning of Dallas','city'=>'Farmers Branch','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-526-8533','website'=>'https://quigleyac.com/%3Futm_source%3Dgoogle%2Bbusiness%2Blisting%26utm_medium%3Dorganic%26utm_campaign%3Dclick%2Bto%2Bwebsite'],
  ['email'=>'seye@suburbanheatandair.com','first_name'=>'Sheree','last_name'=>'Eye','company_name'=>'Suburban Heating & Air Conditioning','city'=>'Dallas','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-381-1127','website'=>'https://www.suburbanheatandair.com/'],
  ['email'=>'andrea@championac.com','first_name'=>'Andrea','last_name'=>'Mcbee','company_name'=>'Champion AC - Climate Magic','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-972-8796','website'=>'https://www.championac.com/air-conditioning/%3Futm_source%3Dgoogle-gbp%26utm_medium%3Dorganic%26utm_campaign%3D*258*champion-ac-san-antonio'],
  ['email'=>'mrosenberg@rosenberghvac.com','first_name'=>'Michael','last_name'=>'Rosenberg','company_name'=>'Rosenberg Plumbing & Air','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-503-7388','website'=>'https://rosenberghvac.com/%3Futm_source%3DGoogle%26utm_medium%3DGBP%26utm_campaign%3DOrganic_GBP_Rosenberg'],
  ['email'=>'sylvia@airsystemsac.com','first_name'=>'Jimenez,','last_name'=>'Sylvia','company_name'=>'AIR SYSTEMS A/C-HEATING AND REFRIGERATION','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-738-2665','website'=>'http://airsystemsac.com/'],
  ['email'=>'maryr@willfixit.com','first_name'=>'Mary','last_name'=>'Roel','company_name'=>'Will Fix It','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-866-8048','website'=>'https://www.willfixit.com/locations%3Futm_source%3Dgoogle%26utm_medium%3Dgbp%26utm_campaign%3Dlocal_seo%26utm_content%3Dgbp_website_click'],
  ['email'=>'samantha@allaboutacandheating.com','first_name'=>'there','last_name'=>'','company_name'=>'All About Air Conditioning & Heating LLC','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-274-1088','website'=>'https://allaboutacandheating.com/'],
  ['email'=>'chrisg@tri-cityac.com','first_name'=>'there','last_name'=>'','company_name'=>'Tri-City A/C & Heating','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-825-0194','website'=>'https://www.tri-cityac.com/'],
  ['email'=>'webrcws@countywideservice.com','first_name'=>'there','last_name'=>'','company_name'=>'County Wide Service Co.- AC, Heating and Plumbing','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-884-4822','website'=>'https://www.countywideservice.com/%3Futm_campaign%3Dgmb%26utm_medium%3Dorganic%26utm_source%3Dgmb'],
  ['email'=>'scheduling@zimmermannservices.com','first_name'=>'there','last_name'=>'','company_name'=>'Zimmermann Air Conditioning & Heating','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-340-8283','website'=>'https://www.zimmermannservices.com/'],
  ['email'=>'manny@airandplumbingtoday.com','first_name'=>'there','last_name'=>'','company_name'=>'Air & Plumbing Today: HVAC Department','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-622-2344','website'=>'https://airandplumbingtoday.com/%3Futm_source%3DGBP%26utm_medium%3Dorganic'],
  ['email'=>'patty@mrwilsonair.com','first_name'=>'Tim','last_name'=>'Wilson','company_name'=>'Mr. Wilson Heating & Air Conditioning','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-308-9866','website'=>'https://www.mrwilsonair.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'potg@jonwayne.com','first_name'=>'there','last_name'=>'','company_name'=>'Jon Wayne Service Company','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 830-217-3095','website'=>'https://jonwayne.com/service-area/san-antonio/%3Futm_source%3Dgoogle-gbp%26utm_medium%3Dorganic%26utm_campaign%3D*432*jon-wayne-san-antonio'],
  ['email'=>'randy.chollar@candjair.com','first_name'=>'Randy','last_name'=>'Chollar','company_name'=>'C & J Air Conditioning & Heating Co','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-340-2665','website'=>'http://candjair.com/'],
  ['email'=>'fbermu@airtegritycs.com','first_name'=>'there','last_name'=>'','company_name'=>'Airtegrity Comfort Solutions','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 210-446-0105','website'=>'https://airtegritycs.com/'],
  ['email'=>'shane@smartairaustin.com','first_name'=>'Shane','last_name'=>'Bryant','company_name'=>'Smart Air Cooling & Heating','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 512-600-4311','website'=>'https://smartairaustin.com/%3Futm_source%3Dgmb%26utm_medium%3Dorganic'],
  ['email'=>'aubrey@eliteaustinac.com','first_name'=>'Aubrey','last_name'=>'Meyer','company_name'=>'Elite Air Conditioning and Plumbing','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-637-4237','website'=>'https://eliteaustinac.com/%3Futm_source%3Dgmb%26utm_medium%3Dlocal%26utm_campaign%3Dwebsite'],
  ['email'=>'corey@austinalpine.com','first_name'=>'Corey','last_name'=>'Thrash','company_name'=>'Alpine Heating & Air Conditioning','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-759-4247','website'=>'https://www.austinalpine.com/'],
  ['email'=>'gdrazic@efficienttexas.com','first_name'=>'George','last_name'=>'Drazic','company_name'=>'Efficient AC, Electric & Plumbing','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-537-4700','website'=>'https://efficienttexas.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dwebsite_link'],
  ['email'=>'hvac@altabra-cooling.com','first_name'=>'there','last_name'=>'','company_name'=>'Altabra Air Conditioning','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-822-9654','website'=>'https://www.altabra-cooling.com/'],
  ['email'=>'youngshvac@keepatxcool.com','first_name'=>'there','last_name'=>'','company_name'=>'Youngs HVAC Pros','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 512-881-2527','website'=>'http://www.keepatxcool.com/'],
  ['email'=>'regan@coolchamps.com','first_name'=>'there','last_name'=>'','company_name'=>'Cool Champs Inc.','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-568-6927','website'=>'http://www.coolchamps.com/'],
  ['email'=>'mteam@masonshvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Masons HVAC & Remodel Services','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 512-845-9702','website'=>'http://www.masonshvac.com/'],
  ['email'=>'randyj@abaaustin.com','first_name'=>'there','last_name'=>'','company_name'=>'ABA Heating and Cooling','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 512-200-9332','website'=>'https://www.abaaustin.com/'],
  ['email'=>'john@hvacmensch.com','first_name'=>'there','last_name'=>'','company_name'=>'hvacMENSCH','city'=>'Austin','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 888-591-4822','website'=>'http://hvacmensch.com/'],
  ['email'=>'sonny@fortworth-air.com','first_name'=>'Sonny','last_name'=>'Pewitt','company_name'=>'Fort Worth Air Conditioning Co. Inc.','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-367-6000','website'=>'https://fortworth-air.com/'],
  ['email'=>'guy.boehler@serviceexperts.com','first_name'=>'Guy','last_name'=>'Boehler','company_name'=>'Service Experts Fort Worth','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-241-5893','website'=>'https://www.serviceexperts.com/fort-worth-tx/%3F%26utm_campaign%3Dlisting%26utm_medium%3Dorganic_search%26utm_source%3Dgmb%26utm_content%3Dbrand'],
  ['email'=>'markw@premierhvacservicesllc.com','first_name'=>'there','last_name'=>'','company_name'=>'Premier HVAC Services LLC','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 469-720-4539','website'=>'https://premierhvacservicesllc.com/%3Futm_source%3Dgbp%26utm_medium%3Dorganic'],
  ['email'=>'rthornton@1stchoiceairsolutions.com','first_name'=>'Rance','last_name'=>'Thornton','company_name'=>'1st Choice Plumbing, Heating & Air Solutions','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-674-1300','website'=>'https://1stchoiceairsolutions.com/%3Futm_source%3Dgoogle%26utm_medium%3Dgbp%26se_campaign%3DGBP'],
  ['email'=>'russ@acserviceandrepairs.com','first_name'=>'there','last_name'=>'','company_name'=>'A/C Service & Repairs, LLC','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-737-8423','website'=>'https://acserviceandrepairs.com/%3Futm_source%3DGBP%26utm_medium%3Dorganic'],
  ['email'=>'albertv@serviceprodfw.com','first_name'=>'there','last_name'=>'','company_name'=>'ServicePro DFW - HVAC','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 682-703-1242','website'=>'https://serviceprodfw.com/'],
  ['email'=>'primetime@primetime-tx.com','first_name'=>'there','last_name'=>'','company_name'=>'Prime Time Heating And Air LLC','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-888-7313','website'=>'https://primetime-tx.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'nicholas@prestigeairtx.com','first_name'=>'there','last_name'=>'','company_name'=>'Prestige Air','city'=>'North Richland Hills','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 817-200-7215','website'=>'http://www.prestigeairtx.com/'],
  ['email'=>'wade@airmotionshvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Air Motions Heating & Air Conditioning','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 214-903-4608','website'=>'https://airmotionshvac.com/'],
  ['email'=>'heather@servicechampstx.com','first_name'=>'there','last_name'=>'','company_name'=>'Service Champs Heating & Air','city'=>'Fort Worth','state'=>'Texas','trade_plural'=>'HVAC companies','phone'=>'+1 682-390-3090','website'=>'https://www.servicechampstx.com/%3Futm_source%3Dgbp%26utm_medium%3Dfort-worth'],
  ['email'=>'terry@truecoolac.com','first_name'=>'Terry','last_name'=>'Zarling','company_name'=>'True Cool Air Conditioning Service Inc','city'=>'South Miami','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 305-232-7575','website'=>'http://www.truecoolac.com/'],
  ['email'=>'eddy@coolsolutionservices.com','first_name'=>'there','last_name'=>'','company_name'=>'Cool Solution Services','city'=>'Miami','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 305-505-0871','website'=>'http://www.coolsolutionservices.com/'],
  ['email'=>'john@hvac-pros-of-miami.com','first_name'=>'there','last_name'=>'','company_name'=>'HVAC pros of Miami','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 305-699-6896','website'=>'http://www.hvac-pros-of-miami.com/'],
  ['email'=>'todd@airondemand.com','first_name'=>'Todd','last_name'=>'Blaylock','company_name'=>'Air On Demand','city'=>'Miami','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 305-259-5669','website'=>'https://www.airondemand.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'gbeldarrain@freezingmechanical.com','first_name'=>'Gilberto','last_name'=>'Beldarrain','company_name'=>'Freezing Mechanical','city'=>'Miami Gardens','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 305-363-7021','website'=>'https://freezingmechanical.com/'],
  ['email'=>'ariel@doctorairhvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Doctor Air Hvac Corp','city'=>'Miami','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 786-367-3152','website'=>'http://www.doctorairhvac.com/'],
  ['email'=>'jamescayton@serviceplusac.com','first_name'=>'there','last_name'=>'','company_name'=>'Service Plus AC & Heating','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 321-277-4408','website'=>'http://www.serviceplusac.com/'],
  ['email'=>'scott.friedberg@mechanicalone.com','first_name'=>'Scott','last_name'=>'Friedberg','company_name'=>'Mechanical One of Orlando - Air Conditioning, Plumbing and Electrical','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-537-2795','website'=>'https://mechanicalone.com/locations/orlando-fl/%3Futm_campaign%3Dgmb'],
  ['email'=>'belleairoffice@belleairac.com','first_name'=>'there','last_name'=>'','company_name'=>'Belle Air','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-543-2050','website'=>'https://belleairac.com/'],
  ['email'=>'shawn@downtown-air.com','first_name'=>'Shawn','last_name'=>'Hoskins','company_name'=>'Downtown Air and Heat','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-408-7105','website'=>'https://downtown-air.com/%3Futm_campaign%3Dgmb'],
  ['email'=>'k.powers@a-1heatandair.com','first_name'=>'there','last_name'=>'','company_name'=>'A-1 HEAT & AIR INC','city'=>'','state'=>'','trade_plural'=>'HVAC companies','phone'=>'+1 407-290-9517','website'=>'https://www.a-1heatandair.com/'],
  ['email'=>'m.duncan@duncansacorlando.com','first_name'=>'Mark','last_name'=>'Duncan','company_name'=>'Duncan\'s Air Conditioning & Heating','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-470-7014','website'=>'https://duncansacorlando.com/'],
  ['email'=>'clark@ecwaters.com','first_name'=>'Clark','last_name'=>'Waters','company_name'=>'E.C. Waters Air Conditioning & Heat','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-603-9144','website'=>'https://ecwaters.com/'],
  ['email'=>'pat@ambroseair.com','first_name'=>'Pat','last_name'=>'Ambrose','company_name'=>'Ambrose Air, Inc.','city'=>'Orlando','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 407-857-0889','website'=>'https://www.ambroseair.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'ac@remairconditioning.com','first_name'=>'there','last_name'=>'','company_name'=>'REM Air Conditioning of Tampa','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-248-5877','website'=>'https://www.remairconditioning.com/'],
  ['email'=>'contractor@rolandoshvac.com','first_name'=>'there','last_name'=>'','company_name'=>'Rolando\'s H.V.A.C.','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-373-6804','website'=>'https://www.rolandoshvac.com/tampa/%3Futm_campaign%3Dgmb%26utm_medium%3Dorganic%26utm_source%3Dgoogle'],
  ['email'=>'scox@thecomfortauthority.com','first_name'=>'Steve','last_name'=>'Cox','company_name'=>'The Comfort Authority','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-461-4819','website'=>'https://www.thecomfortauthority.com/%3Futm_source%3Dgoogle%26utm_medium%3Dgbp'],
  ['email'=>'m.stroz@andservices.com','first_name'=>'Marek','last_name'=>'Stroz','company_name'=>'And Services','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-445-4818','website'=>'https://www.andservices.com/'],
  ['email'=>'m.reyes@alvarezplumbing.com','first_name'=>'Marcus','last_name'=>'Reyes','company_name'=>'Alvarez Plumbing & Air Conditioning','city'=>'Tampa','state'=>'Florida','trade_plural'=>'plumbers','phone'=>'+1 813-213-0533','website'=>'https://www.alvarezplumbing.com/'],
  ['email'=>'snalls@totalairfl.com','first_name'=>'Sean','last_name'=>'Nalls','company_name'=>'Total Air Solutions','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 888-426-1770','website'=>'https://totalairfl.com/'],
  ['email'=>'kenv@youracdoneright.com','first_name'=>'there','last_name'=>'','company_name'=>'Air Conditioning Done Right','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-810-7345','website'=>'http://youracdoneright.com/'],
  ['email'=>'jfabel@hawkinsserviceco.com','first_name'=>'Joe','last_name'=>'Fabel','company_name'=>'Hawkins Service Co.','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-303-1465','website'=>'https://www.hawkinsserviceco.com/%3Futm_source%3Dgoogle%26utm_medium%3Dgbp%26se_campaign%3DGBP-Tampa'],
  ['email'=>'tfarkas@nuccioac.com','first_name'=>'Tony','last_name'=>'Farkas','company_name'=>'Nuccio Heating & Air Conditioning Inc','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-961-7895','website'=>'https://www.nuccioac.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'tim@stellarcoolingservices.com','first_name'=>'there','last_name'=>'','company_name'=>'Stellar Cooling Services','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-360-4052','website'=>'http://www.stellarcoolingservices.com/'],
  ['email'=>'chad@anchorair.net','first_name'=>'Chad','last_name'=>'?','company_name'=>'Anchor Air Conditioning, Inc.','city'=>'Tampa','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 813-260-1017','website'=>'https://www.anchorair.net/'],
  ['email'=>'khunter@hammondair.com','first_name'=>'there','last_name'=>'','company_name'=>'Hammond Heating & Air Conditioning','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-893-3341','website'=>'https://www.hammondair.com/jacksonville-fl/'],
  ['email'=>'coolrus@coolrusnfl.com','first_name'=>'there','last_name'=>'','company_name'=>'Cool R Us, Inc A/C & Heating','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-592-0651','website'=>'https://www.coolrusnfl.com/'],
  ['email'=>'daryl_roy@floridahomeac.com','first_name'=>'Roy,','last_name'=>'Daryl','company_name'=>'Florida Home Air Conditioning','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-990-8633','website'=>'https://floridahomeac.com/service-areas%3Futm_source%3Dgoogle%26utm_medium%3Dgbp%26utm_campaign%3Dlocal_seo%26utm_content%3Dgbp_website_click'],
  ['email'=>'ssnyder@snyderac.com','first_name'=>'Scott','last_name'=>'Snyder','company_name'=>'Snyder Air Conditioning, Plumbing & Electric','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-274-4454','website'=>'https://snyderac.com/north-florida/jacksonville/%3Futm_source%3Dgoogle-gbp%26utm_medium%3Dorganic%26utm_campaign%3D*182*snyder-air-jacksonville'],
  ['email'=>'rgreen@weatherengineers.com','first_name'=>'Ray','last_name'=>'Green','company_name'=>'Weather Engineers','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-593-3721','website'=>'https://weatherengineers.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgbp'],
  ['email'=>'mirza@boldcityac.com','first_name'=>'there','last_name'=>'','company_name'=>'Bold City Heating & Air','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-379-1648','website'=>'https://boldcityac.com/'],
  ['email'=>'mstaggs@nefhac.com','first_name'=>'Mark','last_name'=>'Staggs','company_name'=>'Northeast Florida Heating & Air','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-783-7003','website'=>'https://www.nefhac.com/'],
  ['email'=>'jacob@willmanair.com','first_name'=>'there','last_name'=>'','company_name'=>'Willman Air','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-568-7371','website'=>'https://willmanair.com/'],
  ['email'=>'joejr@thigpenhvac.com','first_name'=>'Joe','last_name'=>'Thigpen','company_name'=>'Thigpen Heating and Cooling','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-448-1962','website'=>'https://www.thigpenhvac.com/%3Fy_source%3D1_MTgwMjQ2NDgtNzE1LWxvY2F0aW9uLndlYnNpdGU%253D'],
  ['email'=>'ben@completeair.com','first_name'=>'Ben','last_name'=>'Bromberg','company_name'=>'Complete Air Systems','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-268-4486','website'=>'http://completeair.com/'],
  ['email'=>'rbittne@tropicaire.net','first_name'=>'Raymond','last_name'=>'Bittner','company_name'=>'Tropic Aire Of North Florida','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-664-2768','website'=>'https://www.tropicaire.net/'],
  ['email'=>'mporter@reliableductsac.com','first_name'=>'there','last_name'=>'','company_name'=>'Reliable Ducts Heating and Cooling','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-551-7132','website'=>'https://reliableductsac.com/'],
  ['email'=>'estimating@hugginsac.com','first_name'=>'there','last_name'=>'','company_name'=>'Huggins Mechanical','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-832-6610','website'=>'http://hugginsac.com/'],
  ['email'=>'bmanning@stradaservices.com','first_name'=>'Brad','last_name'=>'Manning','company_name'=>'Strada Services','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-328-7267','website'=>'https://stradaservices.com/service-area/west-jacksonville-fl/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgmb'],
  ['email'=>'alex@jenkinsheatingandair.com','first_name'=>'Alex','last_name'=>'Jenkins','company_name'=>'Jenkins Heating & Air','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'HVAC companies','phone'=>'+1 904-268-9904','website'=>'http://jenkinsheatingandair.com/'],
  ['email'=>'save@blackstarlandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'Blackstar Landscaping Houston','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 832-464-6669','website'=>'https://www.blackstarlandscaping.com/'],
  ['email'=>'acasso@huatan.us','first_name'=>'there','last_name'=>'','company_name'=>'Huatan Landscaping, LLC','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 832-827-8558','website'=>'http://www.huatan.us/'],
  ['email'=>'mark@lairdlandscaping.com','first_name'=>'Mark','last_name'=>'Sofia','company_name'=>'Laird Landscaping, Inc.','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 281-578-2795','website'=>'https://www.lairdlandscaping.com/'],
  ['email'=>'brad@bdhlandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'BDH Landscaping & Design Company Cypress TX','city'=>'Cypress','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 281-413-9637','website'=>'https://www.bdhlandscaping.com/'],
  ['email'=>'juan@heightsirrigation.com','first_name'=>'there','last_name'=>'','company_name'=>'Houston Heights LLC','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 281-701-4474','website'=>'http://www.heightsirrigation.com/'],
  ['email'=>'jvanos@swplandscaping.com','first_name'=>'Jon','last_name'=>'Vanos','company_name'=>'Southwest Property Landscaping','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 713-661-8887','website'=>'http://www.swplandscaping.com/'],
  ['email'=>'scholarships@lawnstarter.com','first_name'=>'there','last_name'=>'','company_name'=>'LawnStarter - Houston','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 832-981-4636','website'=>'https://www.lawnstarter.com/houston-tx-lawn-care%3Futm_source%3Dgoogle%26utm_medium%3DGLocal%26utm_campaign%3DHoustonLocal'],
  ['email'=>'mnichols@monarchlm.com','first_name'=>'Morris','last_name'=>'Nichols','company_name'=>'Monarch Landscape Management','city'=>'Houston','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 713-849-6600','website'=>'http://www.monarchlm.com/'],
  ['email'=>'sandra@gardensfortexas.com','first_name'=>'there','last_name'=>'','company_name'=>'Gardens for Texas','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 469-330-9987','website'=>'https://gardensfortexas.com/contact'],
  ['email'=>'rafael@earthgreenlands.com','first_name'=>'there','last_name'=>'','company_name'=>'Earth Green Lands','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 214-659-1669','website'=>'https://earthgreenlands.com/%3Futm_source%3Dgoogle%26utm_medium%3Dgoogle-my-business%26utm_campaign%3Dlead%26utm_content%3Dcall-now%26utm_term%3Dlandscaping-dallas'],
  ['email'=>'ddevlin@scapesincorporated.com','first_name'=>'David','last_name'=>'Devlin','company_name'=>'Scapes Incorporated','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 972-371-0328','website'=>'https://www.scapesincorporated.com/'],
  ['email'=>'chuck@cgreens.com','first_name'=>'Chuck','last_name'=>'Green','company_name'=>'CGreens Landscape / Irrigation / Drainage','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 972-231-2870','website'=>'https://www.cgreens.com/'],
  ['email'=>'rebecca@marlinlandscape.com','first_name'=>'Rebecca','last_name'=>'Calley','company_name'=>'Marlin Landscape','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 214-935-3960','website'=>'https://www.marlinlandscape.com/'],
  ['email'=>'greta@princesscutslandscape.com','first_name'=>'there','last_name'=>'','company_name'=>'Princess Cuts Lawncare and Landscaping LLC','city'=>'DeSoto','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 214-893-5709','website'=>'http://www.princesscutslandscape.com/'],
  ['email'=>'denise@splendidgardens.net','first_name'=>'Denise','last_name'=>'Adeucci','company_name'=>'Splendid Gardens Landscaping','city'=>'Lewisville','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 972-898-0030','website'=>'https://splendidgardens.net/'],
  ['email'=>'jeffery.riddle@alterradesignllc.com','first_name'=>'Jeffery','last_name'=>'Riddle','company_name'=>'Alterra Landscape Design','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 214-210-7682','website'=>'https://alterradesignllc.com/'],
  ['email'=>'ismael.r@evergreenlandscapestx.com','first_name'=>'there','last_name'=>'','company_name'=>'Evergreen Sustainable Landscapes LLC','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 469-436-6304','website'=>'http://www.evergreenlandscapestx.com/'],
  ['email'=>'marc@landpatterns.com','first_name'=>'Marc','last_name'=>'Funderburk','company_name'=>'LandPatterns, Inc','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 214-219-3993','website'=>'http://www.landpatterns.com/'],
  ['email'=>'scott@dallaslandscapeandirrigation.com','first_name'=>'Scott','last_name'=>'Garrett','company_name'=>'Dallas Landscape and Irrigation Inc.','city'=>'Dallas','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 214-755-8398','website'=>'http://www.dallaslandscapeandirrigation.com/'],
  ['email'=>'book@canopylandsolutions.com','first_name'=>'there','last_name'=>'','company_name'=>'Canopy Land Solutions','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 218-595-7370','website'=>'https://www.canopylandsolutions.com/'],
  ['email'=>'james@sunriselstexas.com','first_name'=>'there','last_name'=>'','company_name'=>'Sunrise Landscape Services','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 210-903-5507','website'=>'http://www.sunriselstexas.com/'],
  ['email'=>'brian@acacialandscapeanddesign.com','first_name'=>'Brian','last_name'=>'Riebel','company_name'=>'Acacia Landscape and Design','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 830-816-3200','website'=>'http://www.acacialandscapeanddesign.com/'],
  ['email'=>'lance@waterlooturf.com','first_name'=>'there','last_name'=>'','company_name'=>'Waterloo Turf San Antonio','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 210-951-5509','website'=>'https://waterlooturf.com/san-antonio/'],
  ['email'=>'orders@thegrasscompanytx.com','first_name'=>'there','last_name'=>'','company_name'=>'The Grass Company','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 210-622-7225','website'=>'https://thegrasscompanytx.com/'],
  ['email'=>'everavella@everslandscape.com','first_name'=>'there','last_name'=>'','company_name'=>'Ever\'s Landscaping','city'=>'San Antonio','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 210-300-7754','website'=>'https://everslandscape.com/'],
  ['email'=>'clientservices@greeneaselandscapes.com','first_name'=>'there','last_name'=>'','company_name'=>'Green Ease Landscapes & Design','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-551-9381','website'=>'https://www.greeneaselandscapes.com/'],
  ['email'=>'nikk@southernlovelandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'Southern Love Landscaping & Design','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-402-6575','website'=>'https://southernlovelandscaping.com/'],
  ['email'=>'blake@southernlandscape.com','first_name'=>'Blake','last_name'=>'Hearnsberger','company_name'=>'Southern Landscape','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-263-8450','website'=>'https://www.southernlandscape.com/'],
  ['email'=>'david@plantscapesolutions.net','first_name'=>'Plantscape','last_name'=>'Solutions','company_name'=>'Plantscape Solutions','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 512-626-8400','website'=>'https://www.plantscapesolutions.net/'],
  ['email'=>'andrew@terra-dura.com','first_name'=>'there','last_name'=>'','company_name'=>'Terra Dura Landscapes','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-400-4198','website'=>'https://terra-dura.com/'],
  ['email'=>'travis@thrivelandscapedesign.com','first_name'=>'there','last_name'=>'','company_name'=>'Thrive Landscape And Design LLC','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-503-1935','website'=>'http://www.thrivelandscapedesign.com/'],
  ['email'=>'golden@topchoiceaustin.com','first_name'=>'Golden','last_name'=>'Thomas','company_name'=>'Top Choice Lawn Care','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-291-7050','website'=>'http://www.topchoiceaustin.com/'],
  ['email'=>'staci@yarrowlandscaping.com','first_name'=>'Staci','last_name'=>'Duhan','company_name'=>'Yarrow Landscaping Design + Build','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-694-7392','website'=>'https://www.yarrowlandscaping.com/'],
  ['email'=>'bobby@bladerunneratx.com','first_name'=>'there','last_name'=>'','company_name'=>'Blade Runner Landscapes','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-222-2200','website'=>'https://www.bladerunneratx.com/%3Futm_source%3Dgoogle%26utm_medium%3Dwix_google_business_profile%26utm_campaign%3D1349185315177809134'],
  ['email'=>'holler@deweylawns.com','first_name'=>'there','last_name'=>'','company_name'=>'Dewey Lawns','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-355-0994','website'=>'https://deweylawns.com/'],
  ['email'=>'amy@edenaustin.com','first_name'=>'there','last_name'=>'','company_name'=>'Eden Garden Design','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 954-288-7928','website'=>'http://edenaustin.com/'],
  ['email'=>'julie@fertilegroundgardens.com','first_name'=>'Julie','last_name'=>'Donie','company_name'=>'Fertile Ground Gardens','city'=>'Austin','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 512-340-0432','website'=>'https://fertilegroundgardens.com/'],
  ['email'=>'andy@rockviewlandscapes.com','first_name'=>'there','last_name'=>'','company_name'=>'Rockview Landscapes','city'=>'Bee Cave','state'=>'Texas','trade_plural'=>'landscapers','phone'=>'+1 737-404-9079','website'=>'https://www.rockviewlandscapes.com/%3Futm_campaign%3Dgmb'],
  ['email'=>'lucas@condelandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'Conde Landscaping Services, INC.','city'=>'Miami','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 305-223-0041','website'=>'http://condelandscaping.com/'],
  ['email'=>'mike@thoseplantguys.com','first_name'=>'there','last_name'=>'','company_name'=>'Those Plant Guys','city'=>'Miami','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 786-247-5439','website'=>'http://thoseplantguys.com/'],
  ['email'=>'agrillo@cricketpavers.com','first_name'=>'there','last_name'=>'','company_name'=>'Cricket Pavers Outdoor Living of Miami','city'=>'Miami','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 305-925-8124','website'=>'https://cricketpavers.com/%3Futm_source%3DGMBlisting%26utm_medium%3Dorganic'],
  ['email'=>'joe@groundsource.pro','first_name'=>'there','last_name'=>'','company_name'=>'Ground Source Landscaping','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-734-5366','website'=>'https://groundsource.pro/'],
  ['email'=>'yosef@orlandoevergreen.com','first_name'=>'there','last_name'=>'','company_name'=>'Orlando Evergreen Lawn & Landscaping','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-890-7575','website'=>'http://orlandoevergreen.com/'],
  ['email'=>'mb@ncglandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'NCG Landscape & Lawn Maintenance LLC','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-823-7497','website'=>'http://www.ncglandscaping.com/'],
  ['email'=>'firsthand@firsthandlawns.com','first_name'=>'there','last_name'=>'','company_name'=>'Firsthand Landscape, LLC','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-584-3784','website'=>'https://firsthandlawns.com/%3Futm_source%3Dgoogle%26utm_medium%3Dseo%26utm_campaign%3Dgbp-listing'],
  ['email'=>'lisette@bladerunnersorlando.com','first_name'=>'Lisette','last_name'=>'Ortiz','company_name'=>'Blade Runners Commercial Landscaping, Inc','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-306-0600','website'=>'http://bladerunnersorlando.com/'],
  ['email'=>'mai@signaturelandscapecontractors.com','first_name'=>'Mai','last_name'=>'Swanson','company_name'=>'Signature Landscape Contractors, LLC.','city'=>'Maitland','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-622-0011','website'=>'https://www.signaturelandscapecontractors.com/%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dgmb'],
  ['email'=>'john@johnmadisonlandscape.com','first_name'=>'John','last_name'=>'Madison','company_name'=>'John Madison Landscape Inc','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-935-9151','website'=>'http://www.johnmadisonlandscape.com/'],
  ['email'=>'charles@outdoorservicesfl.com','first_name'=>'there','last_name'=>'','company_name'=>'Outdoor Service Inc','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-737-3525','website'=>'http://outdoorservicesfl.com/'],
  ['email'=>'maureen@landforminc.com','first_name'=>'Maureen','last_name'=>'Haggerty','company_name'=>'Landform of Central Florida','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 407-298-3036','website'=>'http://www.landforminc.com/'],
  ['email'=>'edmond@floridalandscapelc.com','first_name'=>'there','last_name'=>'','company_name'=>'Florida Landscape & Lawn Care, LLC','city'=>'Orlando','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 321-257-8320','website'=>'https://www.floridalandscapelc.com/'],
  ['email'=>'parker@centrallandcare.com','first_name'=>'there','last_name'=>'','company_name'=>'Central Land Care','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-765-5296','website'=>'http://www.centrallandcare.com/'],
  ['email'=>'drake@southernoutdoorliving.co','first_name'=>'there','last_name'=>'','company_name'=>'Southern Outdoor Living','city'=>'Largo','state'=>'Florida','trade_plural'=>'home service companies','phone'=>'+1 727-543-3995','website'=>'https://southernoutdoorliving.co/'],
  ['email'=>'friedel@soholandscape.com','first_name'=>'there','last_name'=>'','company_name'=>'Soho Landscape','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-503-9020','website'=>'http://www.soholandscape.com/'],
  ['email'=>'efrain.vazquez@southernfloridalandscaping.com','first_name'=>'Efrain','last_name'=>'Vazquez','company_name'=>'Southern Florida Landscaping','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-486-3727','website'=>'http://www.southernfloridalandscaping.com/'],
  ['email'=>'mcarrillo@cflonline.com','first_name'=>'Carrillo,','last_name'=>'Michael A','company_name'=>'Central Florida Landscaping','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-623-1771','website'=>'http://cflonline.com/'],
  ['email'=>'bissett@myorganicturf.com','first_name'=>'there','last_name'=>'','company_name'=>'My Organic Turf','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 813-957-4440','website'=>'http://www.myorganicturf.com/'],
  ['email'=>'yourfriends@blancosturf.com','first_name'=>'there','last_name'=>'','company_name'=>'Blanco\'s Turf & Landscaping LLC','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-536-7670','website'=>'http://www.blancosturf.com/'],
  ['email'=>'romay@greenimageservices.com','first_name'=>'Romay','last_name'=>'Venta','company_name'=>'Green Image Services','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 813-333-3940','website'=>'http://www.greenimageservices.com/'],
  ['email'=>'bsimms@merionls.com','first_name'=>'there','last_name'=>'','company_name'=>'Merion Landscape Services','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-374-6408','website'=>'https://merionls.com/'],
  ['email'=>'erin@baycut.net','first_name'=>'there','last_name'=>'','company_name'=>'Landscape Workshop','city'=>'Tampa','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 813-265-9400','website'=>'http://baycut.net/'],
  ['email'=>'tana@cllandscape.com','first_name'=>'Tana','last_name'=>'Hamburger','company_name'=>'C & L Landscape','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-353-6620','website'=>'https://www.cllandscape.com/'],
  ['email'=>'andy@serenoagardendesign.com','first_name'=>'there','last_name'=>'','company_name'=>'Serenoa Landscape Design','city'=>'Jacksonville Beach','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-608-7296','website'=>'http://www.serenoagardendesign.com/'],
  ['email'=>'letsgrow@waccapilatka.com','first_name'=>'there','last_name'=>'','company_name'=>'Wacca Pilatka LLC','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-315-8519','website'=>'https://www.waccapilatka.com/'],
  ['email'=>'matt@trutco.com','first_name'=>'Matt','last_name'=>'Siprelle','company_name'=>'Trutco','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-303-7285','website'=>'https://www.trutco.com/'],
  ['email'=>'shaub@prodesignsfl.com','first_name'=>'there','last_name'=>'','company_name'=>'Pro Designs Landscaping','city'=>'','state'=>'','trade_plural'=>'landscapers','phone'=>'+1 904-704-4441','website'=>'https://prodesignsfl.com/'],
  ['email'=>'mike@libertylandscapesupply.com','first_name'=>'Mike','last_name'=>'Zaffaroni','company_name'=>'Liberty Landscape Supply at Trad\'s','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-733-7549','website'=>'http://www.libertylandscapesupply.com/'],
  ['email'=>'jair.luis@havanajaxlandscaping.com','first_name'=>'there','last_name'=>'','company_name'=>'Havana Jax Landscaping Inc.','city'=>'Jacksonville','state'=>'Florida','trade_plural'=>'landscapers','phone'=>'+1 904-400-9793','website'=>'https://havanajaxlandscaping.com/']
];

echo "=== Create Batch 05 ===\n".($confirm?"MODE: CREATE\n\n":"MODE: DRY-RUN (nothing created)\n\n");
echo "Leads to upload: ".count($leads)."  + seed: $SEED\n\n";

$src=crm_instantlyRequest('GET','/campaigns/'.$BATCH02_ID);
if(!$src['ok']){echo "GET Batch 02 FAILED: http={$src['http']} {$src['error']}\n";exit;}
$s=$src['data'];
$steps=$s['sequences'][0]['steps']??[];
echo "Cloning from: \"{$s['name']}\"\n";
echo "  email steps: ".count($steps).", email-1 variants: ".count($steps[0]['variants']??[])."\n";
echo "  text_only=".json_encode($s['text_only']??null)." open_tracking=".json_encode($s['open_tracking']??null)." stop_on_reply=".json_encode($s['stop_on_reply']??null)." unsub_header=".json_encode($s['insert_unsubscribe_header']??null)."\n";
echo "  mailboxes: ".implode(', ',$s['email_list']??[])."\n";
echo "  custom_variables: ".json_encode($s['custom_variables']??null)."\n";
echo "  -> Batch 05 daily_limit set to $DAILY_LIMIT (ramp).\n\n";

if(!$confirm){echo "Dry-run done. Verify the var names + sequence above, then re-run with &confirm=1.\n";exit;}

$payload=array_filter([
  'name'=>$NAME,
  'campaign_schedule'=>['schedules'=>[[
    'name'=>'Default','timing'=>['from'=>'09:00','to'=>'16:00'],
    'days'=>['0'=>false,'1'=>true,'2'=>true,'3'=>true,'4'=>true,'5'=>true,'6'=>false],
    'timezone'=>'America/Detroit',
  ]]],
  'sequences'=>$s['sequences']??null,
  'email_list'=>$s['email_list']??null,
  'daily_limit'=>$DAILY_LIMIT,
  'text_only'=>$s['text_only']??true,
  'open_tracking'=>false,'link_tracking'=>false,
  'stop_on_reply'=>$s['stop_on_reply']??true,
  'stop_on_auto_reply'=>$s['stop_on_auto_reply']??true,
  'insert_unsubscribe_header'=>$s['insert_unsubscribe_header']??true,
  'email_gap'=>$s['email_gap']??null,
  'random_wait_max'=>$s['random_wait_max']??null,
  'prioritize_new_leads'=>$s['prioritize_new_leads']??null,
  'custom_variables'=>$s['custom_variables']??null,
], fn($v)=>$v!==null);

$c=crm_instantlyRequest('POST','/campaigns',$payload);
if(!$c['ok']){echo "CREATE FAILED: http={$c['http']} {$c['error']} raw=".substr(json_encode($c['data']),0,500)."\n";exit;}
$cid=$c['data']['id']??null;
echo "CREATED Batch 05: id=$cid\n";
if(!$cid){echo "no id returned, raw=".substr(json_encode($c['data']),0,300)."\n";exit;}

$seedLead=['email'=>$SEED,'first_name'=>'Leo','last_name'=>'Seed','company_name'=>'Adverton QA','city'=>'Houston','state'=>'Texas','trade_plural'=>'HVAC companies'];
$all=$leads; $all[]=$seedLead;
$ok=0;$err=0;
echo "uploading: ";
foreach($all as $L){
  $email=$L['email']; unset($L['email']);
  if(isset($L['trade_plural'])){$L['tradePlural']=$L['trade_plural'];unset($L['trade_plural']);} // Instantly var is camelCase
  $r=crm_instantlyAddLead($cid,$email,$L);
  if($r['ok']){$ok++; echo ".";} else {$err++; echo "x"; if($err<=3)echo "[{$r['error']}]";}
  @flush();
}
echo "\n\nDONE. Uploaded $ok leads".($err?" ($err errors)":"")." to Batch 05 (DRAFT, daily_limit $DAILY_LIMIT).\n";
echo "NEXT (your rules): in Instantly send a TEST of BOTH email-1 variants to your inbox, confirm rendering+footer+merge tags, THEN activate. Seed $SEED is in the list. Mailboxes are shared with Batch 01-03 — watch combined volume.\n";
